Ensure curl is installed
Currently, this module does not install curl when necessary. In fact,
the entry to install curl has been commented out.

    Error: Could not find command 'curl'
    Error: /Stage[main]/Docker_compose/Exec[download-docker-compose]/returns: change from notrun to 0 failed: Could not find command 'curl'
    Notice: /Stage[main]/Docker_compose/Exec[move-docker-compose]: Dependency Exec[download-docker-compose] has failures: true
    Warning: /Stage[main]/Docker_compose/Exec[move-docker-compose]: Skipping because of failed dependencies
    Notice: /Stage[main]/Docker_compose/File[/usr/local/bin/docker-compose]: Dependency Exec[download-docker-compose] has failures: true
    Warning: /Stage[main]/Docker_compose/File[/usr/local/bin/docker-compose]: Skipping because of failed dependencies

This commit ensures curl is installed using ensure_packages to avoid
conflicts because of duplicate declarations of the same package.